// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nhom7_DoAn_DangKy_DangNhap.Data;

#nullable disable

namespace Nhom7_DoAn_DangKy_DangNhap.Migrations
{
    [DbContext(typeof(Nhom7_DoAn_DangKy_DangNhapContext))]
    [Migration("20250716092529_DoAnDatVeXemPhim")]
    partial class DoAnDatVeXemPhim
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiTK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenDangNhap");

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            TenDangNhap = "admin1",
                            MatKhau = "Admin@123",
                            TrangThaiTK = "Hoạt động",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            TenDangNhap = "use1",
                            MatKhau = "User@123",
                            TrangThaiTK = "Hoạt động",
                            VaiTro = "KhachHang"
                        },
                        new
                        {
                            TenDangNhap = "admin2",
                            MatKhau = "Secure456",
                            TrangThaiTK = "Đã khóa",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            TenDangNhap = "use2",
                            MatKhau = "User456",
                            TrangThaiTK = "Đã khóa",
                            VaiTro = "KhachHang"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
