// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nhom7_DoAn_DangKy_DangNhap.Data;

#nullable disable

namespace Nhom7_DoAn_DangKy_DangNhap.Migrations
{
    [DbContext(typeof(Nhom7_DoAn_DangKy_DangNhapContext))]
    [Migration("20250726030403_CSDLVeXemPhim")]
    partial class CSDLVeXemPhim
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.Ghe", b =>
                {
                    b.Property<string>("TenGhe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaPhongChieu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLoaiGhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TenGhe", "MaPhongChieu");

                    b.HasIndex("MaLoaiGhe");

                    b.HasIndex("MaPhongChieu");

                    b.ToTable("Ghe");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.LoaiGhe", b =>
                {
                    b.Property<string>("MaLoaiGhe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenLoaiGhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiGhe");

                    b.ToTable("LoaiGhe");

                    b.HasData(
                        new
                        {
                            MaLoaiGhe = "LG01",
                            TenLoaiGhe = "Ghế thường"
                        },
                        new
                        {
                            MaLoaiGhe = "LG02",
                            TenLoaiGhe = "Ghế VIP"
                        },
                        new
                        {
                            MaLoaiGhe = "LG03",
                            TenLoaiGhe = "Ghế đôi"
                        });
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.LoaiPhong", b =>
                {
                    b.Property<string>("MaLoaiPhong")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuongGhe")
                        .HasColumnType("int");

                    b.HasKey("MaLoaiPhong");

                    b.ToTable("LoaiPhong");

                    b.HasData(
                        new
                        {
                            MaLoaiPhong = "LP01",
                            SoLuongGhe = 80
                        },
                        new
                        {
                            MaLoaiPhong = "LP02",
                            SoLuongGhe = 40
                        },
                        new
                        {
                            MaLoaiPhong = "LP03",
                            SoLuongGhe = 40
                        });
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.NguoiDung", b =>
                {
                    b.Property<string>("MaNguoiDung")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDung");

                    b.HasData(
                        new
                        {
                            MaNguoiDung = "ND01",
                            Email = "huy246@gmail.com",
                            HoTen = "Nguyễn Gia Huy",
                            SDT = "0901234567"
                        },
                        new
                        {
                            MaNguoiDung = "ND02",
                            Email = "loantran@gmail.com",
                            HoTen = "Trần Thị Loan",
                            SDT = "0912345678"
                        },
                        new
                        {
                            MaNguoiDung = "ND03",
                            Email = "vanan@gmail.com",
                            HoTen = "Lê Văn An",
                            SDT = "0923456789"
                        },
                        new
                        {
                            MaNguoiDung = "ND04",
                            Email = "haiduong707@gmail.com",
                            HoTen = "Nguyễn An Hải Đường",
                            SDT = "0934567890"
                        },
                        new
                        {
                            MaNguoiDung = "ND05",
                            Email = "haichi0710@gmail.com",
                            HoTen = "Hoàng Phương Hải Chi ",
                            SDT = "0923456366"
                        },
                        new
                        {
                            MaNguoiDung = "ND06",
                            Email = "minhnguyen113@gmail.com",
                            HoTen = "Nguyễn Hoàng Nhật Minh ",
                            SDT = "0324567890"
                        });
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.Phim", b =>
                {
                    b.Property<string>("MaPhim")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Anh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DaoDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayKhoiChieu")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThoiLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhim");

                    b.HasIndex("TenDangNhap");

                    b.ToTable("Phim");

                    b.HasData(
                        new
                        {
                            MaPhim = "P01",
                            Anh = "dat-rung-phuong-nam.jpg ",
                            DaoDien = "Nguyễn Quang Dũng",
                            MoTa = "Một cuộc phiêu lưu trong rừng U Minh Hạ",
                            NgayKhoiChieu = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin2",
                            TenPhim = "Đất Rừng Phương Nam",
                            TheLoai = "Phiêu lưu",
                            ThoiLuong = 120
                        },
                        new
                        {
                            MaPhim = "P02",
                            Anh = "bo-gia.jpg",
                            DaoDien = "Trấn Thành ",
                            MoTa = "Câu chuyện về một người cha và cuộc sống Sài Gòn xưa",
                            NgayKhoiChieu = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin1",
                            TenPhim = "Bố già",
                            TheLoai = "Hài",
                            ThoiLuong = 100
                        },
                        new
                        {
                            MaPhim = "P03",
                            Anh = "chuyen-doi-bac-si-noi-tru.jpg",
                            DaoDien = "Joo Dong-min ",
                            MoTa = "Kể về cuộc sống và tình bạn của các bác sĩ nội trú khoa sản tại bệnh viện Yulje, chi nhánh Jongno",
                            NgayKhoiChieu = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin1",
                            TenPhim = "Chuyện đời bác sĩ ngoại trú ",
                            TheLoai = "Phim y khoa, tình cảm",
                            ThoiLuong = 150
                        },
                        new
                        {
                            MaPhim = "P04",
                            Anh = "phim-han-quoc-ve-gioi-thuong-luu-kdrama-penthouse.jpg",
                            DaoDien = "Joo Dong-min",
                            MoTa = "Cuộc chiến ngầm giữa các gia đình giàu có để giành địa vị và quyền lực, với những âm mưu, thủ đoạn và bi kịch đan xen",
                            NgayKhoiChieu = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin2",
                            TenPhim = "Cuộc chiến thượng lưu  ",
                            TheLoai = "Chính kịch, tâm lý xã hội và gật gân",
                            ThoiLuong = 120
                        },
                        new
                        {
                            MaPhim = "P05",
                            Anh = "lat-mat-6.jpg",
                            DaoDien = "Lý Hải",
                            MoTa = "Cuộc đấu trí kịch tính và những cú lật bất ngờ",
                            NgayKhoiChieu = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin2",
                            TenPhim = "Lật mặt 6",
                            TheLoai = "Hành động",
                            ThoiLuong = 130
                        },
                        new
                        {
                            MaPhim = "P06",
                            Anh = "linh-mieu-quy-nhap-trang.jpg",
                            DaoDien = "Lưu Thành Luân",
                            MoTa = "Xoay quanh câu chuyện về Linh Miêu, một loài mèo đen có khả năng nhìn thấy thế giới tâm linh và những hiện tượng siêu nhiên.",
                            NgayKhoiChieu = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin2",
                            TenPhim = "Linh Miêu: Quỷ Nhập Tràng",
                            TheLoai = "Kinh dị",
                            ThoiLuong = 120
                        });
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.PhongChieu", b =>
                {
                    b.Property<string>("MaPhongChieu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLoaiPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhongChieu");

                    b.HasIndex("MaLoaiPhong");

                    b.ToTable("PhongChieu");

                    b.HasData(
                        new
                        {
                            MaPhongChieu = "PC1",
                            MaLoaiPhong = "LP01",
                            TenPhong = "Phòng 1 (Thường)"
                        },
                        new
                        {
                            MaPhongChieu = "PC2",
                            MaLoaiPhong = "LP02",
                            TenPhong = "Phòng 2 (VIP)"
                        },
                        new
                        {
                            MaPhongChieu = "PC3",
                            MaLoaiPhong = "LP03",
                            TenPhong = "Phòng 3 (Couple)"
                        });
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.SuatChieu", b =>
                {
                    b.Property<string>("MaSuatChieu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MaPhim")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaPhongChieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayChieu")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("ThoiGianChieu")
                        .HasColumnType("time");

                    b.HasKey("MaSuatChieu");

                    b.HasIndex("MaPhim");

                    b.HasIndex("MaPhongChieu");

                    b.ToTable("SuatChieu");

                    b.HasData(
                        new
                        {
                            MaSuatChieu = "SC1",
                            GiaVe = 100000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC2",
                            GiaVe = 120000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC3",
                            GiaVe = 160000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC4",
                            GiaVe = 140000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC5",
                            GiaVe = 200000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC6",
                            GiaVe = 150000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC7",
                            GiaVe = 100000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC8",
                            GiaVe = 120000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC9",
                            GiaVe = 160000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC10",
                            GiaVe = 140000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC11",
                            GiaVe = 200000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC12",
                            GiaVe = 150000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC13",
                            GiaVe = 100000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC14",
                            GiaVe = 120000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC15",
                            GiaVe = 160000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC16",
                            GiaVe = 140000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC17",
                            GiaVe = 200000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC18",
                            GiaVe = 150000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC19",
                            GiaVe = 100000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC20",
                            GiaVe = 120000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC21",
                            GiaVe = 160000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC22",
                            GiaVe = 140000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC23",
                            GiaVe = 200000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC24",
                            GiaVe = 150000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC25",
                            GiaVe = 100000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC26",
                            GiaVe = 120000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC27",
                            GiaVe = 160000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC28",
                            GiaVe = 140000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC29",
                            GiaVe = 200000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC30",
                            GiaVe = 150000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC31",
                            GiaVe = 100000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC32",
                            GiaVe = 120000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC33",
                            GiaVe = 160000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC34",
                            GiaVe = 140000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC35",
                            GiaVe = 200000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC36",
                            GiaVe = 150000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC37",
                            GiaVe = 100000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC38",
                            GiaVe = 120000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC39",
                            GiaVe = 160000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC40",
                            GiaVe = 140000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC41",
                            GiaVe = 200000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC42",
                            GiaVe = 150000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC43",
                            GiaVe = 100000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC44",
                            GiaVe = 120000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC45",
                            GiaVe = 160000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC46",
                            GiaVe = 140000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC47",
                            GiaVe = 200000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC48",
                            GiaVe = 150000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC49",
                            GiaVe = 100000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC50",
                            GiaVe = 120000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC51",
                            GiaVe = 160000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC52",
                            GiaVe = 140000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC53",
                            GiaVe = 200000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC54",
                            GiaVe = 150000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC55",
                            GiaVe = 100000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC56",
                            GiaVe = 120000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC57",
                            GiaVe = 160000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC58",
                            GiaVe = 140000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC59",
                            GiaVe = 200000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC60",
                            GiaVe = 150000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC61",
                            GiaVe = 100000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC62",
                            GiaVe = 120000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC63",
                            GiaVe = 160000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC64",
                            GiaVe = 140000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC65",
                            GiaVe = 200000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC66",
                            GiaVe = 150000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC67",
                            GiaVe = 100000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC68",
                            GiaVe = 120000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC69",
                            GiaVe = 160000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC70",
                            GiaVe = 140000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC71",
                            GiaVe = 200000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC72",
                            GiaVe = 150000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC73",
                            GiaVe = 100000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC74",
                            GiaVe = 120000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC75",
                            GiaVe = 160000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC76",
                            GiaVe = 140000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC77",
                            GiaVe = 200000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC78",
                            GiaVe = 150000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC79",
                            GiaVe = 100000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC80",
                            GiaVe = 120000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC81",
                            GiaVe = 160000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC82",
                            GiaVe = 140000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC83",
                            GiaVe = 200000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC84",
                            GiaVe = 150000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC85",
                            GiaVe = 100000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC86",
                            GiaVe = 120000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC87",
                            GiaVe = 160000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC88",
                            GiaVe = 140000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC89",
                            GiaVe = 200000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC90",
                            GiaVe = 150000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC91",
                            GiaVe = 100000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC92",
                            GiaVe = 120000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC93",
                            GiaVe = 160000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC94",
                            GiaVe = 140000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC95",
                            GiaVe = 200000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC96",
                            GiaVe = 150000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC97",
                            GiaVe = 100000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC98",
                            GiaVe = 120000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC99",
                            GiaVe = 160000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC100",
                            GiaVe = 140000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC101",
                            GiaVe = 200000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC102",
                            GiaVe = 150000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC103",
                            GiaVe = 100000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC104",
                            GiaVe = 120000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC105",
                            GiaVe = 160000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC106",
                            GiaVe = 140000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC107",
                            GiaVe = 200000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC108",
                            GiaVe = 150000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC109",
                            GiaVe = 100000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC110",
                            GiaVe = 120000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC111",
                            GiaVe = 160000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC112",
                            GiaVe = 140000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC113",
                            GiaVe = 200000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC114",
                            GiaVe = 150000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC1",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC115",
                            GiaVe = 100000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC116",
                            GiaVe = 120000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC117",
                            GiaVe = 160000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC118",
                            GiaVe = 140000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC119",
                            GiaVe = 200000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC120",
                            GiaVe = 150000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC2",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC121",
                            GiaVe = 100000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC122",
                            GiaVe = 120000m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC123",
                            GiaVe = 160000m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC124",
                            GiaVe = 140000m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC125",
                            GiaVe = 200000m,
                            MaPhim = "P05",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC126",
                            GiaVe = 150000m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC3",
                            NgayChieu = new DateTime(2025, 8, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoLanDangNhapSai")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianKhoa")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiTK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenDangNhap");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique();

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            TenDangNhap = "admin1",
                            IsLocked = false,
                            MaNguoiDung = "ND06",
                            MatKhau = "Admin@123",
                            SoLanDangNhapSai = 0,
                            TrangThaiTK = "Hoạt động",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            TenDangNhap = "use1",
                            IsLocked = false,
                            MaNguoiDung = "ND01",
                            MatKhau = "User@123",
                            SoLanDangNhapSai = 0,
                            TrangThaiTK = "Hoạt động",
                            VaiTro = "KhachHang"
                        },
                        new
                        {
                            TenDangNhap = "admin2",
                            IsLocked = false,
                            MaNguoiDung = "ND05",
                            MatKhau = "Secure456",
                            SoLanDangNhapSai = 0,
                            TrangThaiTK = "Đã khóa",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            TenDangNhap = "use2",
                            IsLocked = false,
                            MaNguoiDung = "ND04",
                            MatKhau = "User456",
                            SoLanDangNhapSai = 0,
                            TrangThaiTK = "Đã khóa",
                            VaiTro = "KhachHang"
                        },
                        new
                        {
                            TenDangNhap = "loantran456",
                            IsLocked = false,
                            MaNguoiDung = "ND02",
                            MatKhau = "Pass@456",
                            SoLanDangNhapSai = 0,
                            TrangThaiTK = "Hoạt động",
                            VaiTro = "KhachHang"
                        },
                        new
                        {
                            TenDangNhap = "an789",
                            IsLocked = false,
                            MaNguoiDung = "ND03",
                            MatKhau = "Pass@789",
                            SoLanDangNhapSai = 0,
                            TrangThaiTK = "Hoạt động",
                            VaiTro = "KhachHang"
                        });
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.ThanhToan", b =>
                {
                    b.Property<string>("MaThanhToan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaVe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VeMaVe")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaVe");

                    b.HasIndex("VeMaVe");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.Ve", b =>
                {
                    b.Property<string>("MaVe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GheMaPhongChieu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GheTenGhe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaPhongChieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSuatChieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenGhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVe");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaSuatChieu");

                    b.HasIndex("GheTenGhe", "GheMaPhongChieu");

                    b.HasIndex("TenGhe", "MaPhongChieu");

                    b.ToTable("Ve");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.Ghe", b =>
                {
                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.LoaiGhe", "LoaiGhe")
                        .WithMany("Ghes")
                        .HasForeignKey("MaLoaiGhe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.PhongChieu", "PhongChieu")
                        .WithMany("Ghes")
                        .HasForeignKey("MaPhongChieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiGhe");

                    b.Navigation("PhongChieu");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.Phim", b =>
                {
                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TenDangNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.PhongChieu", b =>
                {
                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.LoaiPhong", "LoaiPhong")
                        .WithMany()
                        .HasForeignKey("MaLoaiPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.SuatChieu", b =>
                {
                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.Phim", "Phim")
                        .WithMany("SuatChieus")
                        .HasForeignKey("MaPhim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.PhongChieu", "PhongChieu")
                        .WithMany()
                        .HasForeignKey("MaPhongChieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phim");

                    b.Navigation("PhongChieu");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.TaiKhoan", b =>
                {
                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.NguoiDung", "NguoiDung")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("Nhom7_DoAn_DangKy_DangNhap.Models.TaiKhoan", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.ThanhToan", b =>
                {
                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.Ve", null)
                        .WithMany()
                        .HasForeignKey("MaVe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.Ve", "Ve")
                        .WithMany()
                        .HasForeignKey("VeMaVe");

                    b.Navigation("Ve");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.Ve", b =>
                {
                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.NguoiDung", "NguoiDung")
                        .WithMany("Ves")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.SuatChieu", "SuatChieu")
                        .WithMany("Ves")
                        .HasForeignKey("MaSuatChieu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.Ghe", "Ghe")
                        .WithMany()
                        .HasForeignKey("GheTenGhe", "GheMaPhongChieu");

                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.Ghe", null)
                        .WithMany()
                        .HasForeignKey("TenGhe", "MaPhongChieu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ghe");

                    b.Navigation("NguoiDung");

                    b.Navigation("SuatChieu");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.LoaiGhe", b =>
                {
                    b.Navigation("Ghes");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.NguoiDung", b =>
                {
                    b.Navigation("TaiKhoan");

                    b.Navigation("Ves");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.Phim", b =>
                {
                    b.Navigation("SuatChieus");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.PhongChieu", b =>
                {
                    b.Navigation("Ghes");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.SuatChieu", b =>
                {
                    b.Navigation("Ves");
                });
#pragma warning restore 612, 618
        }
    }
}
