// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nhom7_DoAn_DangKy_DangNhap.Data;

#nullable disable

namespace Nhom7_DoAn_DangKy_DangNhap.Migrations
{
    [DbContext(typeof(Nhom7_DoAn_DangKy_DangNhapContext))]
    partial class Nhom7_DoAn_DangKy_DangNhapContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.Ghe", b =>
                {
                    b.Property<string>("TenGhe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaPhongChieu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLoaiGhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TenGhe", "MaPhongChieu");

                    b.HasIndex("MaLoaiGhe");

                    b.HasIndex("MaPhongChieu");

                    b.ToTable("Ghe");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.LoaiGhe", b =>
                {
                    b.Property<string>("MaLoaiGhe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenLoaiGhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiGhe");

                    b.ToTable("LoaiGhe");

                    b.HasData(
                        new
                        {
                            MaLoaiGhe = "LG01",
                            TenLoaiGhe = "Ghế thường"
                        },
                        new
                        {
                            MaLoaiGhe = "LG02",
                            TenLoaiGhe = "Ghế VIP"
                        },
                        new
                        {
                            MaLoaiGhe = "LG03",
                            TenLoaiGhe = "Ghế đôi"
                        });
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.LoaiPhong", b =>
                {
                    b.Property<string>("MaLoaiPhong")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuongGhe")
                        .HasColumnType("int");

                    b.HasKey("MaLoaiPhong");

                    b.ToTable("LoaiPhong");

                    b.HasData(
                        new
                        {
                            MaLoaiPhong = "Thuong",
                            SoLuongGhe = 80
                        },
                        new
                        {
                            MaLoaiPhong = "VIP",
                            SoLuongGhe = 40
                        },
                        new
                        {
                            MaLoaiPhong = "Couple",
                            SoLuongGhe = 40
                        });
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.NguoiDung", b =>
                {
                    b.Property<string>("MaNguoiDung")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDung");

                    b.HasData(
                        new
                        {
                            MaNguoiDung = "ND01",
                            Email = "huy246@gmail.com",
                            HoTen = "Nguyễn Gia Huy",
                            SDT = "0901234567"
                        },
                        new
                        {
                            MaNguoiDung = "ND02",
                            Email = "loantran@gmail.com",
                            HoTen = "Trần Thị Loan",
                            SDT = "0912345678"
                        },
                        new
                        {
                            MaNguoiDung = "ND03",
                            Email = "vanan@gmail.com",
                            HoTen = "Lê Văn An",
                            SDT = "0923456789"
                        },
                        new
                        {
                            MaNguoiDung = "ND04",
                            Email = "haiduong707@gmail.com",
                            HoTen = "Nguyễn An Hải Đường",
                            SDT = "0934567890"
                        },
                        new
                        {
                            MaNguoiDung = "ND05",
                            Email = "haichi0710@gmail.com",
                            HoTen = "Hoàng Phương Hải Chi ",
                            SDT = "0923456366"
                        },
                        new
                        {
                            MaNguoiDung = "ND06",
                            Email = "minhnguyen113@gmail.com",
                            HoTen = "Nguyễn Hoàng Nhật Minh ",
                            SDT = "0324567890"
                        });
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.Phim", b =>
                {
                    b.Property<string>("MaPhim")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Anh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DaoDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayKhoiChieu")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThoiLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhim");

                    b.HasIndex("TenDangNhap");

                    b.ToTable("Phim");

                    b.HasData(
                        new
                        {
                            MaPhim = "P01",
                            Anh = "dat-rung-phuong-nam.jpg ",
                            DaoDien = "Nguyễn Quang Dũng",
                            MoTa = "Một cuộc phiêu lưu trong rừng U Minh Hạ",
                            NgayKhoiChieu = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin2",
                            TenPhim = "Đất Rừng Phương Nam",
                            TheLoai = "Phiêu lưu",
                            ThoiLuong = 120
                        },
                        new
                        {
                            MaPhim = "P02",
                            Anh = "bo-gia.jpg",
                            DaoDien = "Trấn Thành ",
                            MoTa = "Câu chuyện về một người cha và cuộc sống Sài Gòn xưa",
                            NgayKhoiChieu = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin1",
                            TenPhim = "Bố già",
                            TheLoai = "Hài",
                            ThoiLuong = 100
                        },
                        new
                        {
                            MaPhim = "P03",
                            Anh = "chuyen-doi-bac-si-noi-tru.jpg",
                            DaoDien = "Joo Dong-min ",
                            MoTa = "Kể về cuộc sống và tình bạn của các bác sĩ nội trú khoa sản tại bệnh viện Yulje, chi nhánh Jongno",
                            NgayKhoiChieu = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin1",
                            TenPhim = "Chuyện đời bác sĩ ngoại trú ",
                            TheLoai = "Phim y khoa, tình cảm",
                            ThoiLuong = 150
                        },
                        new
                        {
                            MaPhim = "P04",
                            Anh = "phim-han-quoc-ve-gioi-thuong-luu-kdrama-penthouse.jpg",
                            DaoDien = "Joo Dong-min",
                            MoTa = "Cuộc chiến ngầm giữa các gia đình giàu có để giành địa vị và quyền lực, với những âm mưu, thủ đoạn và bi kịch đan xen",
                            NgayKhoiChieu = new DateTime(2022, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin2",
                            TenPhim = "Cuộc chiến thượng lưu  ",
                            TheLoai = "Chính kịch, tâm lý xã hội và gật gân",
                            ThoiLuong = 120
                        },
                        new
                        {
                            MaPhim = "P05",
                            Anh = "lat-mat-6.jpg",
                            DaoDien = "Lý Hải",
                            MoTa = "Cuộc đấu trí kịch tính và những cú lật bất ngờ",
                            NgayKhoiChieu = new DateTime(2022, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin2",
                            TenPhim = "Lật mặt 6",
                            TheLoai = "Hành động",
                            ThoiLuong = 130
                        },
                        new
                        {
                            MaPhim = "P06",
                            Anh = "linh-mieu-quy-nhap-trang.jpg",
                            DaoDien = "Lưu Thành Luân",
                            MoTa = "Xoay quanh câu chuyện về Linh Miêu, một loài mèo đen có khả năng nhìn thấy thế giới tâm linh và những hiện tượng siêu nhiên.",
                            NgayKhoiChieu = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin2",
                            TenPhim = "Linh Miêu: Quỷ Nhập Tràng",
                            TheLoai = "Kinh dị",
                            ThoiLuong = 120
                        });
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.PhongChieu", b =>
                {
                    b.Property<string>("MaPhongChieu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLoaiPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhongChieu");

                    b.HasIndex("MaLoaiPhong");

                    b.ToTable("PhongChieu");

                    b.HasData(
                        new
                        {
                            MaPhongChieu = "PC01",
                            MaLoaiPhong = "Thuong",
                            TenPhong = "Phòng 1"
                        },
                        new
                        {
                            MaPhongChieu = "PC02",
                            MaLoaiPhong = "VIP",
                            TenPhong = "Phòng 2"
                        },
                        new
                        {
                            MaPhongChieu = "PC03",
                            MaLoaiPhong = "Couple",
                            TenPhong = "Phòng 3"
                        });
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.SuatChieu", b =>
                {
                    b.Property<string>("MaSuatChieu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MaPhim")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaPhongChieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayChieu")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("ThoiGianChieu")
                        .HasColumnType("time");

                    b.HasKey("MaSuatChieu");

                    b.HasIndex("MaPhim");

                    b.HasIndex("MaPhongChieu");

                    b.ToTable("SuatChieu");

                    b.HasData(
                        new
                        {
                            MaSuatChieu = "SC01",
                            GiaVe = 120000.00m,
                            MaPhim = "P01",
                            MaPhongChieu = "PC01",
                            NgayChieu = new DateTime(2025, 7, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC02",
                            GiaVe = 120000.00m,
                            MaPhim = "P02",
                            MaPhongChieu = "PC01",
                            NgayChieu = new DateTime(2025, 7, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 21, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC03",
                            GiaVe = 150000.00m,
                            MaPhim = "P03",
                            MaPhongChieu = "PC02",
                            NgayChieu = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 21, 0, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC04",
                            GiaVe = 200000.00m,
                            MaPhim = "P04",
                            MaPhongChieu = "PC03",
                            NgayChieu = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 20, 30, 0, 0)
                        },
                        new
                        {
                            MaSuatChieu = "SC05",
                            GiaVe = 120000.00m,
                            MaPhim = "P06",
                            MaPhongChieu = "PC01",
                            NgayChieu = new DateTime(2025, 7, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            ThoiGianChieu = new TimeSpan(0, 22, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiTK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenDangNhap");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique();

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            TenDangNhap = "admin1",
                            IsLocked = false,
                            MaNguoiDung = "ND06",
                            MatKhau = "Admin@123",
                            TrangThaiTK = "Hoạt động",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            TenDangNhap = "use1",
                            IsLocked = false,
                            MaNguoiDung = "ND01",
                            MatKhau = "User@123",
                            TrangThaiTK = "Hoạt động",
                            VaiTro = "KhachHang"
                        },
                        new
                        {
                            TenDangNhap = "admin2",
                            IsLocked = false,
                            MaNguoiDung = "ND05",
                            MatKhau = "Secure456",
                            TrangThaiTK = "Đã khóa",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            TenDangNhap = "use2",
                            IsLocked = false,
                            MaNguoiDung = "ND04",
                            MatKhau = "User456",
                            TrangThaiTK = "Đã khóa",
                            VaiTro = "KhachHang"
                        },
                        new
                        {
                            TenDangNhap = "loantran456",
                            IsLocked = false,
                            MaNguoiDung = "ND02",
                            MatKhau = "Pass@456",
                            TrangThaiTK = "Hoạt động",
                            VaiTro = "KhachHang"
                        },
                        new
                        {
                            TenDangNhap = "an789",
                            IsLocked = false,
                            MaNguoiDung = "ND03",
                            MatKhau = "Pass@789",
                            TrangThaiTK = "Hoạt động",
                            VaiTro = "KhachHang"
                        });
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.ThanhToan", b =>
                {
                    b.Property<string>("MaThanhToan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaVe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VeMaVe")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaVe");

                    b.HasIndex("VeMaVe");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.Ve", b =>
                {
                    b.Property<string>("MaVe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GheMaPhongChieu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GheTenGhe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaPhongChieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSuatChieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenGhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVe");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaSuatChieu");

                    b.HasIndex("GheTenGhe", "GheMaPhongChieu");

                    b.HasIndex("TenGhe", "MaPhongChieu");

                    b.ToTable("Ve");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.Ghe", b =>
                {
                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.LoaiGhe", "LoaiGhe")
                        .WithMany("Ghes")
                        .HasForeignKey("MaLoaiGhe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.PhongChieu", "PhongChieu")
                        .WithMany("Ghes")
                        .HasForeignKey("MaPhongChieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiGhe");

                    b.Navigation("PhongChieu");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.Phim", b =>
                {
                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TenDangNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.PhongChieu", b =>
                {
                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.LoaiPhong", "LoaiPhong")
                        .WithMany()
                        .HasForeignKey("MaLoaiPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.SuatChieu", b =>
                {
                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.Phim", "Phim")
                        .WithMany("SuatChieus")
                        .HasForeignKey("MaPhim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.PhongChieu", "PhongChieu")
                        .WithMany()
                        .HasForeignKey("MaPhongChieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phim");

                    b.Navigation("PhongChieu");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.TaiKhoan", b =>
                {
                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.NguoiDung", "NguoiDung")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("Nhom7_DoAn_DangKy_DangNhap.Models.TaiKhoan", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.ThanhToan", b =>
                {
                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.Ve", null)
                        .WithMany()
                        .HasForeignKey("MaVe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.Ve", "Ve")
                        .WithMany()
                        .HasForeignKey("VeMaVe");

                    b.Navigation("Ve");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.Ve", b =>
                {
                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.NguoiDung", "NguoiDung")
                        .WithMany("Ves")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.SuatChieu", "SuatChieu")
                        .WithMany("Ves")
                        .HasForeignKey("MaSuatChieu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.Ghe", "Ghe")
                        .WithMany()
                        .HasForeignKey("GheTenGhe", "GheMaPhongChieu");

                    b.HasOne("Nhom7_DoAn_DangKy_DangNhap.Models.Ghe", null)
                        .WithMany()
                        .HasForeignKey("TenGhe", "MaPhongChieu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ghe");

                    b.Navigation("NguoiDung");

                    b.Navigation("SuatChieu");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.LoaiGhe", b =>
                {
                    b.Navigation("Ghes");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.NguoiDung", b =>
                {
                    b.Navigation("TaiKhoan");

                    b.Navigation("Ves");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.Phim", b =>
                {
                    b.Navigation("SuatChieus");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.PhongChieu", b =>
                {
                    b.Navigation("Ghes");
                });

            modelBuilder.Entity("Nhom7_DoAn_DangKy_DangNhap.Models.SuatChieu", b =>
                {
                    b.Navigation("Ves");
                });
#pragma warning restore 612, 618
        }
    }
}
